### ISSUE TITLE
User Input (moving smily via keyboard)

### ISSUE THREAD

**Issue by duh102** [CSC510-2015-Axitron/maze#1]
User is able to move play piece on the field

**Comment by duh102** [comment]
Tried putting this in in c4c15aa968, doesn't seem to have worked

**Comment by meneal** [comment]
Perhaps this will end up being a toolchain problem.  Perhaps Canvas is not the best way to go given the  state of the API.  Should we potentially use some other JS framework?

**Comment by macluo** [comment]
I can give it another try tonight while you guys are looking for other.

**Comment by duh102** [comment]
I believe I've actually figured it out, I was getting the size of the canvas wrong, fixed in a2f6f2c0d7
