### ISSUE TITLE
Path breadcrumbs

### ISSUE THREAD

**Issue by duh102** [CSC510-2015-Axitron/maze#10]
When the user moves through the maze, leave a trail showing where the user has previously been and the current path from the entrance

**Comment by macluo** [comment]
Trail feature added but not working at this moment. 7586aa86a369f560c9d417e77c0748f5603dbfe8

**Comment by duh102** [comment]
Fixed it to work as-is (46e4dee4d79a891c35d85d607acc025ed773b35b), but it needs more work (I'm envisioning changing the color of objects when you pass over them again on a backtrack), currently it will overlay extra dots which looks strange (and will probably degrade performance)

**Comment by macluo** [comment]
I will add collision detection mechanism to those dots and hopefully backtrack will work.

**Comment by macluo** [comment]
Added array to track dots. No extra dots will be placed. e5fd2481a57cd1972c50130a08f7e3f042540a52 Searching backtrack algorithm/data structure...

**Comment by duh102** [comment]
Couldn't you mirror the dimensions of the maze and then use that? If visited, utilize array spot, otherwise null.

**Comment by macluo** [comment]
That's what I did but that will remove trail intersect and created a empty spot in between. I am thinking tree structure to store backtracking. Just removed duplicate function 8230568c874c01b95a9de5b042feefb7bed091bb

**Comment by macluo** [comment]
Moved trailModel to separate file. 5931967e6cd638931615fc0fa3ab3cae64c5a769  Let me know if the trail dots flicker when you move the smiley on your browser.

**Comment by macluo** [comment]
Created a new branch backtrack.  727d263f0f3b0f25db9ae00a1d55c05db30d258a 1 parent 61fa9fb
 All backtrack features will be implemented in this new model.

**Comment by macluo** [comment]
Merged backtrack to master 60f51cbc8b896b9c971f5f27661b9452567e5185 Backtrack feature is working, sort of. It still has bugs but I will fix them when the actual maze is loaded to the canvas. The commit history looks a bit weird. Hope that I didn't mess up the merge.

**Comment by duh102** [comment]
I believe you might have merged master into backtrack, but I don't know if that's bad or not lol

**Comment by macluo** [comment]
I did rebase and merge after checked out master branch and thought that should merge backtrack into master. Maybe I was wrong.

**Comment by macluo** [comment]
Forgot to post the update b9e2510b169f94a0e6c7f7dc039cd97a396910a9. Issue is closed for now.
