### ISSUE TITLE
Travis CI

### ISSUE THREAD

**Issue by meneal** [CSC510-2015-Axitron/maze#15]
Would anyone like me to set up Travis CI for the repo?  We don't really have a build script yet so it won't do anything until we do, but it seems like a reasonable thing to add if we plan on doing some scripted building and testing. http://travis-ci.org  It's really an awesome system that will auto build on each push to the repo.

**Comment by macluo** [comment]
Travis CI has my vote. The setup is easier than Jenkins. Haha...

**Comment by duh102** [comment]
Do we need a build system? Javascripts don't need to be compiled or anything, and the tests are all Javascript as well.

**Comment by meneal** [comment]
It's true we actually don't need a build system, but travis ci is so stupid easy that it isn't any real work to set it up.  There's no real building to do, but what we can have travis do is run the tests and then deploy to heroku on each push to the main branch.  

That way we know that all of the tests work on each change and the thing is automatically deployed without any fuss.  I'll set it all up in a branch and if it doesn't work or people don't like it we can always scrap it without much trouble.  It shouldn't take me more than my work time today.

I'm going to close this issue, the testing issue, and the deployment issue and then open a branch issue that has all three inside.

**Comment by macluo** [comment]
I didn't realize this issue had been closed. There are tools that would combine JS files and "compile" them into fewer or single minified files. If the build platform can do that for us that would be cool if our maze program becomes very big. lol

**Comment by meneal** [comment]
True, doesn't grunt handle that?

**Comment by macluo** [comment]
I don't know if grunt does that but if it does maybe we should explore it. lol
