### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by meneal** [CSC510-2015-Axitron/maze#16]
How do we mean to deploy?  We could use some sort of cloud hosting like AWS.  Or potentially could use something like bitnami or heroku to do our deployment.

**Comment by macluo** [comment]
AWS would be a good idea. I think it could also be integrated to Travis-CI, right?

**Comment by meneal** [comment]
It actually looks like Heroku is the way to go for this.  There is some pretty strong Travis CI integration with Heroku where it can auto deploy.  Here's a bit of info: http://docs.travis-ci.com/user/deployment/heroku/

**Comment by duh102** [comment]
So far, the entire application is client-side, so any sort of static web hosting will do. Heck, I have a personal file server running on my server at home and it works fine on that.

**Comment by meneal** [comment]
True, but Heroku is free for something like this and assigns a static web address.  So no one needs to host it, and we can pass it on to the mechanical turk testers without much problem.  The automatic part of it with travis-ci I think makes it a reasonable idea.

**Comment by meneal** [comment]
Closing to put it in with my automatic build branch issue.
