### ISSUE TITLE
Branch Purpose

### ISSUE THREAD

**Issue by meneal** [CSC510-2015-Axitron/maze#18]
Please post the purpose for each branch you have made so that we can keep track of what everyone is doing so as to not duplicate work.

**Comment by duh102** [comment]
mazemodel: branch for development on maze model features
mazerender: branch for development on maze view features
mazeload: branch for working on loading from file (should be complete)
The issues I've assigned myself are the features I've checked out for development, I mark things with "help wanted" when I've hit a bug I'm not sure how to fix.

**Comment by macluo** [comment]
The backtrack branch is to develop different backtrack data structure so when player retracts the trail can be erased. 

One trick to figure out who is working on what is to look at the assignees under each issue report. When an issue has been picked each developer should change the tag and assign the task to himself.

I have created yellow tags to label the JS files being worked on.

One quick question, the testRig.JS in the backtrack branch doesn't give me expected result. It may appear to be broken. Is there a way to just cherry-pick the latest testRig.JS file into my branch to avoid copy & paste or merging the entire branch?

**Comment by duh102** [comment]
You can cherry pick commits but not files, as far as I know. The file is so small, however, that you should just be able to copy the file from master and paste it in without any issue.

**Comment by macluo** [comment]
Thanks! I will go ahead and make a copy. Hopefully it won't confuse Github. Haha...

**Comment by duh102** [comment]
It should just see it as changes to the file, normal commit stuff.

**Comment by meneal** [comment]
Awesome.  This is really helpful.  Should we just leave this open and then when new branches are added just add them to this?

**Comment by duh102** [comment]
I'm uncertain we need it, to be honest. Branch off when you want to develop a new feature and check out features by adding yourself as the assignee, seems like that would cover pretty much all collisions to me. I can certainly explain what my branches are for when I make them though, not a problem.

**Comment by meneal** [comment]
Sounds good to me.  I'll close then.

**Comment by macluo** [comment]
I figured out the test problem originated in my branch so your testRig.JS has been working fine. Thanks for making it easy for us.

**Comment by duh102** [comment]
No problem, glad it's been useful!
