### ISSUE TITLE
Data Format for Maze

### ISSUE THREAD

**Issue by duh102** [CSC510-2015-Axitron/maze#2]
Likely JSON? Need:
num cells
width/height maze
walls
entrance
exit

**Comment by duh102** [comment]
Needs testing but feature conceptually complete in c083a992953f6d0c622d39c0d9698dbce836f3f9

**Comment by macluo** [comment]
I ran a few tests on the maze model and got some errors. Is AMaze an JS object with some nested objects in it?

**Comment by duh102** [comment]
Yes, that part I'm not entirely sure of. The OO Javascript tutorial I read up on [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Introduction_to_Object-Oriented_JavaScript) said that's how you do "packages" or "namespaces" in JS

**Comment by duh102** [comment]
Fixed it up a lot in fdc8d1b26041cb214e00446857502aa6f4021cc6, now there's a test suite for the thing. There's one assertion that's failing and I don't know why, seems that accessibleExits for the model is not working right and I don't know why.

**Comment by macluo** [comment]
Oh! You have fixed it! I cleaned up the mazeModel a bit to make future copy/paste easier. 9839c2fb5ab90f093bd0636aa5491f5d2e21802e

**Comment by duh102** [comment]
Thanks! Merged in my changes that also fixed it that I then reverted because your method is much cleaner.
