### ISSUE TITLE
Prettier Maze

### ISSUE THREAD

**Issue by duh102** [CSC510-2015-Axitron/maze#20]
Maze tile backgrounds to match sprites from http://untamed.wild-refuge.net/rmxpresources.php?characters or similar resources

**Comment by duh102** [comment]
Going to attempt this using this lovely tileset http://opengameart.org/content/dungeon-tileset

**Comment by meneal** [comment]
This is definitely a good idea.

**Comment by duh102** [comment]
Just as an update, I've been investigating this and I'm running into a performance bottleneck with large mazes. I'm investigating solutions but it's not going as well as I had hoped. There's a lot left to try, however, so I'm not discouraged yet.

**Comment by duh102** [comment]
Had to make large changes to the way the renderer works; it now needs two canvases, one for CanvasEngine and one for the maze itself. CanvasEngine handles the player's sprite while the other canvas will be manually drawn to.
This is to get around a limitation of CanvasEngine, where it always re-renders the entire canvas (and everything on it) as often as possible up to 60fps, leading to a huge waste of CPU time. I would almost suggest finding a new engine at this point but I don't know how troublesome that would be. It's a somewhat strange little quirk that I'm uncertain we could figure out about other engines to effectively utilize them. For the time being I'm going to assume we have no engine support for drawing the maze itself, and work around that.
Luckily, since our maze's state doesn't ever change, this is very easily accomplished. I haven't implemented it yet, but you can draw to an in-memory canvas and then draw portions of that canvas as necessary.

**Comment by macluo** [comment]
You mean even on two overlapping scenes with one filled with static components without calling the render() function still affect the other one? I noticed a simple swap of append() function with prepend() also causes the canvas to flicker.

**Comment by duh102** [comment]
The way the engine works, all currently visible scenes render as fast as possible, clearing the entire canvas on each every frame, and it attempts to get a solid 60fps for that. So, even static images such as the maze are redrawn in their entirety every 1/60th of a second. The way I've done it now (you can swap over to this branch to try it out), CanvasEngine only works with the one canvas, the one that has possibly-moving things on it (if we decide to have flickering torches or whatnot), and everything static or seldomly-moving is on the lower canvas, which is manually controlled.

**Comment by macluo** [comment]
I don't know if hacking the Canvas engine would help but this seems to be the code controlling the fps. Maybe we can slow it down. haha...

Line 1386:
                   i._loop()
                        }
                    }
                    requestAnimationFrame(e)
                }
                requestAnimationFrame(e)
            },
            getFPS: function() {
                return ~~this.fps
            },
            getPerformance: function() {
                return ~~(this.getFPS() / 60 * 100)
            }
        }
    });
    Class.create("Canvas", {

**Comment by KdotJPG** [comment]
I don't think that code *controls* the FPS, I think it just reports the FPS.

According to this: http://stackoverflow.com/questions/11943120/html-canvas-interval-vs-requestanimationframe , requestAnimationFrame is called approximately 60 times per second, and I don't think we can control that.

What we DO want to do though is try to avoid putting game logic in requestAnimationFrame.

**Comment by ktspence** [comment]
I don't think that code *controls* the FPS, I think it just reports the FPS.

According to this: http://stackoverflow.com/questions/11943120/html-canvas-interval-vs-requestanimationframe , requestAnimationFrame is called approximately 60 times per second, and I don't think we can control that.

What we DO want to do though is try to avoid putting game logic in requestAnimationFrame.

**Comment by duh102** [comment]
Yeah, I'm just going to let all that sit there. No sense in messing around with the engine. Currently I draw the entire maze to an in-memory canvas and draw portions of it on a background canvas, only refreshing that background canvas when the player moves. The player, actually, never moves at the moment, just always stays in the center of the screen because I was a bit lazy with the math for moving the pieces.

**Comment by duh102** [comment]
I'm exceptionally proud of this screenshot. http://i.imgur.com/vu7CXe0.png

**Comment by meneal** [comment]
Wow!!!  That is awesome man.

**Comment by duh102** [comment]
Gonna close this because what I wanted to accomplish is complete, open new issues for improvements/fixes.
