### ISSUE TITLE
Automatic Build Branch

### ISSUE THREAD

**Issue by meneal** [CSC510-2015-Axitron/maze#21]
I'm creating a new branch to test out building with travis.ci, deployment via heroku, and testing via intern.  I'll make a comment when ready, so that people can check it out and see if it's something we want to use.

**Comment by meneal** [comment]
Intern ended up being a bit of a dead end as the framework required a selenium webdriver, which was quite difficult to get running locally, and all of the available hosted options had prohibitive costs associated with them.  Looking at mocha and phantomjs.  Mocha is the testing platform and phantom is a headless browser for functional tests.

**Comment by meneal** [comment]
Added the first chunk to the autobuild branch.  It took me a LONG time to get working with mocha and  the current existing framework.  What is setup for now is pretty nice actually.    

What you'll need to have to run it:
- npm
- g++

First run:
`npm install`

Next run: 
`make test`

This will give you both the coverage as well as passing tests for mazeModel.js.  I'm working on getting the functional tests working next.  After that I'll set up the deployment and build parts.

**Comment by meneal** [comment]
Automatic build is working now in the branch.  You can click on the badge in the readme to show the actual build.  Functional tests didn't really work out the way I had intended, so as of now I only have the unit tests for mazeModel.js.  But with the current setup that could be extended pretty quickly.  Heroku is the next phase.

**Comment by macluo** [comment]
Wow! That is neat. Thanks.

**Comment by meneal** [comment]
So I'll rewrite the backtrack tests, but after that is everyone willing to switch over to mocha style unit testing?  I can help with any setup issues that anyone might have.  I think for the functional stuff the test rig is still the way to go.

Mocha docs [here]( http://mochajs.org/).
Chai docs [here](http://chaijs.com/).

Chai supports a few different styles of testing.  I'm currently using Assert and Mocha's bdd interface. You can use whatever style of Chai that you prefer, since that can be specified at the beginning of the test file.  It would be good though to stick with bdd across the entire project.  My example of testing isn't super great right now, but if you want to look at it, it is in [here]( https://github.com/CSC510-2015-Axitron/maze/blob/autobuild/test/test-mazeModel.js).

**Comment by meneal** [comment]
Still working on the tests.  There are a few things that really don't work in nodejs since this is browser stuff so I'm trying to figure out how to run mocha in the browser using something called testem.  Just figured I'd add in a bit of an update.

**Comment by meneal** [comment]
So the end is neigh.  I have completed all of the tests for mazeModel and backtrack.  Sorry it took me awhile, but I had to learn a lot to get them done.  Will/Mark:  Please take a look and make sure that everything is tested as you would like.  

One test is definitely broken and I'm going to put it up as a bug.  I'll also split this out into another issue for deployment.

**Comment by macluo** [comment]
Quick question. Do you know where the make rule is located? This node.js and auto build/testing is fun.

**Comment by meneal** [comment]
This is a dumb mistake on my part.  So for now and probably going forward I'll leave off the Makefile and run testing directly from npm.  So for now test function is as follows:

`npm install`
`npm test`

It's possible you'll have to run npm install as sudo.  I'm going to add to the README a short test function section so people know how to test locally.  Sorry I didn't do that earlier!

**Comment by meneal** [comment]
Instructions are posted to the README.

**Comment by macluo** [comment]
Now it works. Thanks.
