### ISSUE TITLE
Suggested Canvas Engine Resources

### ISSUE THREAD

**Issue by meneal** [CSC510-2015-Axitron/maze#22]
Anyone have any suggestions for good resources on Canvas Engine?

**Comment by duh102** [comment]
I've been learning from the documentation on CanvasEngine's website http://canvasengine.net/doc/?p=tuto-get_started.html

**Comment by ktspence** [comment]
Here's an RPG tutorial based on Canvas Engine. Perhaps it will be helpful as well: http://rpgjs.com/v2/doc/?p=tuto-get_started.html
