### ISSUE TITLE
Maze Editor Tool

### ISSUE THREAD

**Issue by ktspence** [CSC510-2015-Axitron/maze#23]
External utility to quickly create mazes by hand. In-browser or platform-independent preferable.

**Comment by ktspence** [comment]
I can write a simple Web-based utility that generates the JSON and puts it in a text field for the user to copypaste from.

**Comment by duh102** [comment]
Editor's looking good!

**Comment by meneal** [comment]
+1

**Comment by macluo** [comment]
Looks great and the tool is very easy to use. Just made a 10x10 maze4 and took me like less than 10 seconds.

**Comment by duh102** [comment]
Since it's merged in and works perfectly fine, closing this.
