### ISSUE TITLE
Improved scrolling math

### ISSUE THREAD

**Issue by ktspence** [CSC510-2015-Axitron/maze#24]
Make it so the player moves instead of the maze "background" when the player is approaching the edge of the maze, so the "camera" doesn't scroll the maze past the boundary.

**Comment by duh102** [comment]
Just wondering if you had time for this @ktspence, or should we push it back to v0.3? We can inject some levels to replace it as a feature for v0.2.

**Comment by ktspence** [comment]
I touched on it a bit but I'm still running into issues understanding all of the parts that I need to change.

**Comment by duh102** [comment]
The movement of the player and maze inside the display canvas is handled inside the the refresh() function in the renderer, it's around line 236 in the latest code for today. I can explain further if you need, but it pretty much just moves the upper left part of the maze so that the current cell (the player's location) is centered in the canvas.

**Comment by duh102** [comment]
Moved this into v0.3, sounded like it needed to be pushed back a bit.

**Comment by meneal** [comment]
Seems like this is pretty much dead.  I hate for us to have this hanging around and making it look like we haven't finished our work.  Should we just close it?

**Comment by ktspence** [comment]
I'm just back from spring break. Give me tonight to see if I can make sense of the errors I've been getting, and if it's not finished by tonight we can close it.

**Comment by ktspence** [comment]
Going to go ahead and close this one actually. The way we're handling the canvas doesn't lend well to this method of scrolling, and I also think that not being able to see a certain amount into the maze is a gameplay element in and of itself that this would be counter to. (In other words, not only is it more trouble than it's worth because we would need to re-write things, it also might be something we don't want in the first place.)
