### ISSUE TITLE
Playable level(s)

### ISSUE THREAD

**Issue by duh102** [CSC510-2015-Axitron/maze#27]
I'd say between 5-10 is a good starting goal for release, but for now just one or two would do nicely.

**Comment by meneal** [comment]
What will a playable level actually mean?  Just talking about what this is in terns of whether it's achievable or not.  Should we say that a playable level would mean that you could move around the maze without it crashing, and then get to the end of the maze and have indication that you have won?

**Comment by duh102** [comment]
Mostly just non-testing levels that are interesting enough for people to actually play. The mocks in the test directory, for example, are not good playable levels.

**Comment by duh102** [comment]
Going to close this and utilize other, more specific, issues to make levels once the designer is complete.
