### ISSUE TITLE
Possible bug in old tests

### ISSUE THREAD

**Issue by meneal** [CSC510-2015-Axitron/maze#29]
When opening the index.html file in test in the master branch there is no output other than the tests running.   Just an empty box where the maze usually is.

I'm moving those tests over to another folder and making a small change to maze model so I wanted to make sure that I'm not breaking anything.

**Comment by macluo** [comment]
Maybe the compatibility issue. Can someone confirm if it is also the case on IE? It works on Safari. I will look into it.

**Comment by macluo** [comment]
Looks like Google Chrome is having the issue. It also displays an empty box on the commits before the merge.

**Comment by meneal** [comment]
Doesn't work in IE either.  The only browser that is working now is Safari.  Any ideas on what could have been incompatible?

**Comment by duh102** [comment]
Are you accessing it using local directives (like file://somethingsomething/maze/test/) ?
Certain operations we're doing (doing ajax calls using ../ and loading images) don't work locally like that, you have to use a local web host like xampp or a local install of apache, or just dump the thing onto a web host.

**Comment by meneal** [comment]
I was actually accessing locally.  I didn't realize that we were needed to use a local webhost at this point since it was working without problems locally before.  If that's the case then this isn't really a bug, I'll close then and push my test changes when I get home.

**Comment by duh102** [comment]
Well, it used to work in Firefox (and I guess Safari?) because it's same origin policy didn't forbid images from ../ but it does forbid doing an ajax call to ../
So now that I load a level from the root maze directory (../levels/whatever) it doesn't work without a web host.

**Comment by duh102** [comment]
I'll mark this as solved with the following remark:
This is happening because I attempted to put all the levels into a directory off of /maze and load a level into the test environment from there (/maze/test), so I used an ajax call to load a level from ../levels/something/levelsomething.json, which breaks if you attempt to use the files locally rather than hosted.

**Comment by meneal** [comment]
So, I found a nice quick way to serve files locally that is really lightweight.  I'm not sure that it'll be of use to others, but I found it really nice.  Here's how it works:

You need to have npm.  If you have it you run:

` npm install http-server -g`

Then move into the root maze directory and run:  
`http-server -d --cors`

That loads up a server on http://localhost:8080, which has the same directory structure as the root directory does.  So for example at http://localhost:8080/OldTest/index.html you'll see that working perfectly.  It also deals with some weird errors you get from loading across directories like Will was talking about.  That's the cors option you'll see at the end.  Documentation is [here](https://github.com/nodeapps/http-server).
