### ISSUE TITLE
Deployment to Heroku

### ISSUE THREAD

**Issue by meneal** [CSC510-2015-Axitron/maze#30]
This is a new branch for deployment to Heroku.  Hopefully won't take a super long time.

**Comment by meneal** [comment]
Good news.  I've switched to Divshot for our deployment and I have it working.  It's really simple for now.  Just shows the map that we had in the OldTest folder's index.html.  I pulled the test rig stuff out of it.  

So to run with divshot you have to actually set up a public folder, so I set that up with everything needed just to run the simple thing that I have up there right now.  This is only on the autodeploy branch.  I can demo it tomorrow so everyone knows how it works, but it's all done. 

Here's the deployed to it running right now:  http://development.maze.divshot.io/

For now as long as it passes these tests it will deploy.  I'll move this over to the master if everyone is in agreement tomorrow.  One weird side effect is that the divshot server can't seem to figure out the folder names for the levels.  So if you look in public/levels/ you'll see that I changed the name of the folder to remove the (5-10).

**Comment by duh102** [comment]
The parens or hyphen probably freaked it out. Perfectly fine by me, I only put that in to be more specific about the sizes.

**Comment by meneal** [comment]
And now this is complete and merged.  You can see the deployed maze with the maze menu at the link above.  I merged it for real this time too!

**Comment by macluo** [comment]
Just pushed the bug-fixed backtrack.js to both master branch and the public folder. Hopefully Divshot will get the update. LOL
