### ISSUE TITLE
maze loading test broken

### ISSUE THREAD

**Issue by meneal** [CSC510-2015-Axitron/maze#31]
[Here](https://github.com/CSC510-2015-Axitron/maze/blob/master/test/test-mazeModel.js) on line 84 you'll see a comment that that test is hopelessly broken.  

The problem is some sort of issue with the way that I'm calling the mazeModel.load() method.  I'm not sure why it doesn't work.  I assume that it has something to do with the fact that everything is happening in node though.  If anyone wants to take a stab at it, it would be awesome.  The really annoying thing is that if you run the tests that test is completely left out so there isn't any output.

**Comment by macluo** [comment]
This is not related to mazeModel.load() but I would also like to suggest maybe moving the following code from models to their parent js file.

if (typeof window === "undefined")
    var $ = require('jquery')(require("jsdom").jsdom().parentWindow);

the reason simply is JSLint stops working when it reads these first two lines.

**Comment by meneal** [comment]
Actually to test using node the way I am currently this is the only way.
The thing is that $ is undefined otherwise in node.  I tried requiring it
in the test file, but that doesn't work.  Backtrack doesn't require jquery
so we can just pull that out of there.  I just did that and pushed it to
master.

In the browser jquery is being pulled in by the html file, but node uses
require.  If you can figure out a way to avoid it I'm all for it, but I
don't think there is a way right now.

I'm working on testing entirely in the browser though and at that point we
won't need those blocks.  It might never work completely with TravisCI
though.

**Comment by meneal** [comment]
JSHint actually works with the way things are currently.  I can actually add that in to the npm test script, do you think that's a good idea?

**Comment by macluo** [comment]
I see. If JSHint works, yes please add that. I don't know JSHint or JSLint, which one is better but as long as we have one there it should be good enough. Haha… Just checked out JSHint on npm and it had 299174 downloads last week. It must be very good!

**Comment by meneal** [comment]
It's a really nice tool.  I think one thing to decide is how it should
actually run.  I can add it on to the regular npm test script, but I'm not
sure that's the best idea.  I'll work with it for awhile this afternoon.

**Comment by meneal** [comment]
I've added this functionality to the autodeploy branch.  I have it running in two different ways.  With JShint you can set up whatever reporter you want.  What it comes with it isn't so hot.  So I've set up two reporters so we can pick one we end up liking.  Here are the links to the reporters:

[jshint stylish](https://github.com/sindresorhus/jshint-stylish)
[jshint html reporter](https://github.com/adrianpietka/jshint-html-reporter)

You can run the command line one with this command:

`npm jshint-cli`

The reporter one is coded into the test script, so you can run:

`npm test`

Once that is run, in the root directory you'll see a file called report.html.  That file has the jshint report in it.  It doesn't look that great, but at least it's something.  jshint stylish is pretty nice looking actually.  

Two other things:

- What files are linted is controlled by the .jshintignore file.  Whatever is in there is ignored by jshint obviously.

- .jshintrc is the config file.  If you're feeling frisky you can get in there and make some changes.  This one is stolen from some random website.  It has the stuff I need for mocha tests at the top, but aside from that change at will.  The bitwise & seems to piss it off, LOL.

**Comment by macluo** [comment]
Just test ran JSHint and it spit out fewer warnings compared to JSLint. :) No wonder JSLint website warns its users that it could hurt people's feelings. LOL

**Comment by duh102** [comment]
Did we ever fix this?

**Comment by meneal** [comment]
Honestly I figured out a way to fix this and neglected to actually push
it.  I'll try to fix it now.  I think I might have to reinvent the wheel a
bit to do it, but it's not too big of a deal.  I think it can be done using
promises.

**Comment by meneal** [comment]
I thought I could fix this, but I actually could only ever get it working in the browser.  So if you checkout browserTest, go to OldTest and run

  http-server --cors

And then open the file test.html, you'll see that all of the tests are passing.  Creating the same structure with  the server and everything only results in the first test passing.  I get all of these weird errors that say: 
  
  TypeError: Object [object Object] has no method 'accessibleExits'

I'm hoping that the changeover to db access should make it easier to actually do this testing.  It seems to be a jquery thing and not anything to do with async testing since the async test works in the browser, node just has some problem with it.  I'll leave it as is and then try to rework after loading is done through the db.

**Comment by macluo** [comment]
I can help with this issue if @meneal is busy with db setup as I have dealt with it when creating test files for mazeMenu.js One reason if failed because Mocha doesn't know how to process jquery methods and other function calls related to the browser. The workaround is to create mock objects. Because we are not supposed to test jQuery itself, creating mock objects to test the features within our codebase should suffice.

Is it the following code producing the errors?

```javascript
//loads JSON data from disk (same filesystem as stored on)
	//calls func on success with loaded maze as param
	load: function(filename, func) {
		$.getJSON( filename, {}, function( data ) {
			var load = new AMaze.model.Maze();
			load.width = data.width;
			load.height = data.height;
			load.start = data.start;
			load.currPos = [data.start[0], data.start[1]];
			load.end = data.end;
			load.board = data.board;
			func(load);
		});
	}
```

**Comment by meneal** [comment]
That's the code.  I think one way of dealing with it is using sinonjs' spy
ability to produce those mocks.  I looked at that a bit last night and
couldn't get it rolling.  I would love to see how it works, or any other
mock data way you can get it working.

**Comment by macluo** [comment]
This is the $ function I used. To actually make $.getJSON() work, you can add a getJSON() method in it

```
$ = function(obj) {

	var components = {
		0: {
			width: function() {return 40;},
			height: function() {return 10;}
		},
		css: function(a,b) {
			//set css here
		},
		text: function(a) {
			this.dummpyDsp = a;
		}
	}
	
	if (typeof obj == 'string') {

		if (obj.match(/^#.+/)) //check if obj is html components
		{
			components.click = function(a) {
				a();
			}
			return components;
		}
		else
			return components;
	}
	else if (typeof obj == 'function')
	{
		obj();
	}
	else
	{
		obj.on = function() {return obj;}
		obj.scrollTop = function(a) {return obj;}
		obj.scrollLeft = function(a) {return obj;}

		return obj;
	}
}
```

**Comment by macluo** [comment]
Just modified jQuery mock object to cover mazeModel test a46b1d2eede52e4528194ee72a882593a37b63dc. There are still two assertion failed that I have commented out in test-mazeModel.js It is related to how array is being parsed as the reason for failing the test is 

AssertionError: expected [ 0, 1 ] to equal [ 0, 1 ]

Must be it is the datatype.

**Comment by meneal** [comment]
Switch the assert to "deepEqual" instead of "equal", that should take care
of it.

**Comment by macluo** [comment]
You are right. :+1: Now all work now. 863e67d2aac3f80a3d4d46754b7be1a76c34cfba

**Comment by meneal** [comment]
Awesome.  We can close this out then!
