### ISSUE TITLE
Divshot DB?

### ISSUE THREAD

**Issue by duh102** [CSC510-2015-Axitron/maze#32]
As title: can we do a DB With Divshot? If so, which ones?

**Comment by duh102** [comment]
Made a [preliminary ERD](https://github.com/CSC510-2015-Axitron/maze/blob/0776f875c90f98e78384417ed5482d13ea6bc45b/images/db_ERD.png) for if/when we get an ERD.

**Comment by meneal** [comment]
We're using Firebase for our db needs.  Information is [here](https://www.firebase.com/).
