### ISSUE TITLE
Animated Knight

### ISSUE THREAD

**Issue by ktspence** [CSC510-2015-Axitron/maze#33]
Replace the static sprite used for the player with an animated character with multiple walking frames, and different facing directions.

**Comment by macluo** [comment]
Anyone likes to create animated knight may add your implementation after line 304 in mazeRender.js.

```
// Knight animation code can go here!
// Allow Async so no blocking!
AMaze.render.FPS_handler = setInterval(function(){

  var that = AMaze.render;
  ++that.FPScounter;

  if (that.FPScounter <= that.framePerStep) {

       bgCtx = that.bgCanvas.getContext('2d');
```

**Comment by meneal** [comment]
I'm not so sure we really have time to do this at this point, and given the size of the knight and the sort of throwback game we have anyway, this might not be worth it.  It was my idea, but now I'm just not so sure.  Let me know if you have an opinion and we can close it out  if we don't want it.

**Comment by duh102** [comment]
Yeah I think we should just mark it as won'tfix, I'll go do that.
