### ISSUE TITLE
Music

### ISSUE THREAD

**Issue by ktspence** [CSC510-2015-Axitron/maze#35]
Add music to the game. Most likely different tracks for:
- Menu
- In-game

May or may not want more than one track to be played in levels. Need to figure out how it is determined which track plays in each level if we do have more than one track.

**Comment by macluo** [comment]
Music should play when maze finishes loading 59e0a99fa332a6412574dd806309d597987e3fa9. Let me know if it will take too long for the music to play. The mp3 file in the sound directory can be replaced. So feel free to experiment it. There is an issue with Canvas's sound engine. When a music is being played, there seems to be no way to kill it unless I have missed something.

**Comment by macluo** [comment]
Maze should play music now when it finishes loading 59e0a99fa332a6412574dd806309d597987e3fa9. Let me know if it will take too long for the music to play. The mp3 file in the sound directory can be replaced. So feel free to experiment it. There is an issue with Canvas's sound engine. When a music is being played, there seems to be no way to kill it unless I have missed something.

**Comment by macluo** [comment]
Music continues to play regardless of levels. Open a new case if you guys want that changed. Anyway, this ticket is closed for now.
