### ISSUE TITLE
Additional Tileset

### ISSUE THREAD

**Issue by ktspence** [CSC510-2015-Axitron/maze#36]
Add an additional tileset.

Some levels will use the exsting tileset, and some levels will use the new tileset.

**Comment by duh102** [comment]
As with #37, I'm claiming this but I won't be able to work on it until Thursday, so if anyone else really REALLY wants to jump in and claim it they can.

**Comment by duh102** [comment]
Going to make a nice grassy path tileset.

**Comment by duh102** [comment]
Done, that was both easier and harder than last time. Made the sheet just a single tile-per-cell sheet, which simplified the json but complicated the image editing.
http://i.imgur.com/ok9Hpv3.png

**Comment by meneal** [comment]
Looks really nice man.

**Comment by duh102** [comment]
At some point in the future, maybe next milestone, I should look into being able to switch the tilesets without changing the source. For now I'm marking this done.
