### ISSUE TITLE
Save states to DB

### ISSUE THREAD

**Issue by ktspence** [CSC510-2015-Axitron/maze#37]
Whichever system we end up using for our DB,  a means of saving our game state to the DB, and restoring it.

**Comment by duh102** [comment]
I'll claim this for now but if anyone else wants to jump on it (I won't be able to work much on it until Thursday at the earliest) feel free to reassign.

**Comment by duh102** [comment]
So, to be clear, this is:
* the level you're on
* the location of your player
* the time
* the steps
* the trail you've performed

or is it some subset of that?

**Comment by macluo** [comment]
You might want to include the score. You may find those variables in the gameData() function of mazeMenu.js

Currently there is no interface for importing and exporting the backtrack model (backtrack.model.tree) and trail dot array in trailModel (trailModel.theBoard) but it can be done and may need to invoke forwardSearch() to find the pointer in backtrack model. Alternatively, we can make the player always begin at the starting point when loading the saved level.

Let me know which task I can help with. I took the easy jobs this time and have finished score and music. LOL

**Comment by duh102** [comment]
I'm partially thinking maybe we shouldn't bother saving game state, just remove the save/load buttons and instead save high scores for each completed maze. I'm just unsure how good of a feature being able to pause in the middle of a maze is...

**Comment by macluo** [comment]
I agree. Saving high scores and highest level etc would be the minimum, but I am okay with either case. If you want to be able to save/load the game in the middle of maze, I can make trailModel & backtrack work that way. Maybe we can also add a button for the designer?

**Comment by meneal** [comment]
I would say that the most useful thing would be being able to save only what level you are on and the score.  I wouldn't think anything else would be that important.  

Thinking about this from a player standpoint it would be nice to be able to walk away from the game (close your browser or whatever) and then come back and play in the same level again.

That could really nicely be implemented by just saving the level and score to the user's data and not even bother having any save state.  Then it would be a better user experience I'd think:  A user would come to the site, login, and then be back at the last level they were at with the score they had.  But no need to actually save a specific position.  Seems like that way we could pull the buttons, and then save that for milestone 4.

**Comment by duh102** [comment]
Ok, so I'm going to change this feature to be: saving the last level the player was "on" (meaning, not solved yet) and the amount of time/steps it took to complete a level if they have completed it.

**Comment by duh102** [comment]
I'm going to close this because it somewhat falls out of tracking which levels the user has completed in a category.
