### ISSUE TITLE
High Scores

### ISSUE THREAD

**Issue by ktspence** [CSC510-2015-Axitron/maze#38]
Implement a high score system. Should display on user interface, and should involve the DB.

**Comment by macluo** [comment]
Currently there are four pieces of info are displayed on the game menu: level, time, steps, and lives. The last one is to limit the number of attempts the player can have. If we do not want this feature, I can change it to display high score. Any suggestion?

**Comment by duh102** [comment]
Yeah I'm uncertain we can really work lives in unless we have a pursuer, having it be "shortest time" or something would be better I think.

**Comment by macluo** [comment]
Maze now displays high score instead of "lives" 224f620a88364fff8dc3109da4e6646953b525eb To save and restore user data to Firebase may utilize gameData() object.

**Comment by macluo** [comment]
The score formula for the level is Math.round(50 * (1 + currentMaze * 0.6) - currentStep - currentTime * 3), where currentMaze is the maze number, currentStep and currentTime are the total steps and time spent on the current level. Feel free to change the formula as you see fit. I will close this for now.
