### ISSUE TITLE
Loops break backtrack

### ISSUE THREAD

**Issue by duh102** [CSC510-2015-Axitron/maze#39]
Traveling in a loop messes with the backtracking, only testable on the third maze.

**Comment by macluo** [comment]
Overlay is now enabled on trailModel. 74d2daf4e99c30ff786a5e149ced5d7bf078a882  Player may circle many times but the trail will be removed as soon as player backtracks. Let me know if this is desirable. The backtrack.js can actually memorize how many circles the player has made so it is possible to create overlay footsteps etc.

**Comment by macluo** [comment]
Both traveling and backtracking in loops now work. d69f832ebb8deef04a5309a92e6c55c736bc75b6
