### ISSUE TITLE
Should we have a simple web framework set up for our maze?

### ISSUE THREAD

**Issue by macluo** [CSC510-2015-Axitron/maze#4]
I am thinking may be either Web2Py or Ruby on Rails. Just a thought.

**Comment by duh102** [comment]
I'm uncertain it would be any more helpful than the current framework, is everyone more able to code in python or ruby than javascript?

**Comment by meneal** [comment]
From what Mark was saying it seems like this isn't a language change it's just a framework for directory structure and organization.  I'm excited to see the demo branch of it.

**Comment by macluo** [comment]
Just added AngularJS to the repo. Thought this might be useful for building single webpage app in the future. Right now Web2Py or Rails is too heavy weight I guess.

**Comment by meneal** [comment]
Two other's to possibly consider are ember and backbone.js.  It's looking like Angular is the best way to go though.   I will close I if can't find any evidence to the contrary.

**Comment by meneal** [comment]
We've decided on Angular.js so I guess at this point we should start a new issue for actually setting up the web framework if it comes up in deployment.
