### ISSUE TITLE
Set up DB

### ISSUE THREAD

**Issue by meneal** [CSC510-2015-Axitron/maze#40]
Export level data to database, wireframe for ERD Will posted earlier.

**Comment by meneal** [comment]
I just took a first stab at it.  If anyone feels like it, check out what I have so far in the db.  I'll be refining it from here and trying to get actual calls figured out.  Let me know if you have a particular opinion on it though.  I know we need more than just levels, but we can add everything else once we can get levels and queries working the way we want.  

You may notice some weird duplication of effort stuff up here, but as far as I can tell that is actually the right way to do it.  A short best practices article is [here](https://www.firebase.com/docs/web/guide/structuring-data.html).  Didn't give me great information so I'm having to figure most of it out on my own.

**Comment by duh102** [comment]
I've been working on accessing it, and it's not terribly hard. The biggest difficulty will be ensuring that the database is set up properly initially, and that we check that it is before attempting to access it. After that you can just request parts of it using a URL.
One thing I noticed is that you actually used the board as a full JSON object rather than serializing it, do you have a reason for that or was it just easy? I'm uncertain at present which is better. Serializing it would be nicer to look at from a management perspective (since at that point it'd just be a string) but it'd add a layer of complication when loading it.
I've pushed my demo of loading the database (just prints out the entire contents of the DB) in 3970c29c8e32c30664c08714ec26bb8bf2fe2623, in case anyone wants to look at it.

**Comment by macluo** [comment]
Thanks for the link. This is very helpful as it helped me get started. Since the level_data contains height and width, perhaps it might be better just serialize each maze level because the entire maze data must be downloaded as a whole anyway. But it also means the designers must convert all the indexes of the cells to double digits.

**Comment by macluo** [comment]
Just created user_idx, user_data, and user_pass 3 JSON objects on Firebase. Here login ID (e.g., DemoID) will be used as the key. Please comment and feel free to edit them. We should also decide whether user-created contents should be public or not etc.

**Comment by duh102** [comment]
I would think that user-created levels should be public for others to play, though perhaps only if you have a code for it? Meaning, when you create a level, it's put into the DB but with a little flag that says it's not reachable unless you have the level id for it, kinda like private videos on Youtube.
Either that or we could physically separate them, with two different areas for user-created levels and included levels.

**Comment by meneal** [comment]
I'm not much of a dba.  What would serializing them look like?  I did just
leave them as is because it was the easiest way.

**Comment by duh102** [comment]
It's pretty easy for JSON, pretty much just outputting the JSON as a string instead of putting it in as an object. I believe it's as easy as JSON.stringify(object), and to go from serialized to JSON, JSON.parse(string).

**Comment by meneal** [comment]
Oh I gotcha.  I actually hand wrote the first addition in Json and imported
it.  I could write some little script to serialize I think or find
something to do it.  Is that definitely what we want?

**Comment by macluo** [comment]
Just created user_levels object following @meneal 's level structure. I have also added security & rules to Firebase.com. Feel free to modify it. I removed user_pass sine Firebase stores users' passwords by itself. The next step would be to test them.

**Comment by macluo** [comment]
Firebase doesn't provide useful API function to convert $level to numeric when defining rules on the server. Any idea how to work around it?

**Comment by macluo** [comment]
Found the solution. Used $level < '5'

**Comment by duh102** [comment]
I've just now been able to work on this, but I'm confused on what each object does.
I understand the need for having duplicate data between levels and groups (to speed up access between group membership and such), but I'm unclear on why (levels and level_data) and (user_data and user_idx) are separate, and I'm also uncertain what user_stat is for.
I can understand separating 1st party levels from user levels, in which case, is it just going to be a structural copy of our level scheme but specific to a user?

**Comment by macluo** [comment]
Object user_data is to store game status of each players with both read/write permissions while user_idx is to store profile info such as create_date, first & last name etc where users only have read permission. User_levels and user_level_data is to store user-created contents. User_levels only store names of the mazes to construct directory while user_level_data contains the actual maze data. User_stat is to store highest score of the all players and other game statistics that we might be interested. Hope my explanation makes sense and again feel free to change them as you see fit.

**Comment by macluo** [comment]
The rules for accessing those objects are defined [here] (https://axemaze.firebaseio.com/?page=Security). My testing shows that some of the rules do not seem to work and I don't know why.

**Comment by duh102** [comment]
So I've been thinking and I think a noSQL database like Firebase is not really what we want. We want to do a lot of relational things (associating users with user-created levels, levels with groups, users with levels via if they've completed it/how long it took) and not a lot of document things (storing level data). As of this moment (just woke up) I haven't found a free relational DB service but I really think we should utilize both a relational and a document service because of the different things we need to use.
Doing relational DB stuff in noSQL is difficult and can lead to data mismatch if you aren't very careful, and I think that's a headache we should try to avoid.
If we can't find a cloud-hosted solution (I saw Amazon has one we can use for 12 months but it needs a credit card and stuff, even for the free solution), I can gladly host a MySQL server on my machine, or we can attempt to get something going on NCSU's servers (do they do node?).

**Comment by meneal** [comment]
I really have to agree.  Seems like we are trying to fit a square peg into
a round hole with this.  Sorry I haven't been able to do more on it.  It's
been really quite hard to work out of town like this.  I'm heading home
today and will be back to it late this afternoon.  I'll look around a bit
then and see if it can't find something other than having you use your own
server.

**Comment by meneal** [comment]
Heroku offers Postgres, would that suit our needs better?   I think it's
free but didn't have time to confirm.

**Comment by duh102** [comment]
Postgres would work fine, perfectly fine.

**Comment by meneal** [comment]
Cool I'll confirm cost this afternoon and get everyone access.

**Comment by meneal** [comment]
So I'm totally out of my element on this.  I have almost no experience with databases, so I'm trying to learn this on the fly and I really am not having a whole lot of luck. 

The thing with Heroku is that it does not allow for organization wide access, so we'd have to either set up a dummy account or have one person have the account and no one else would have access.  Also I'm not completely sure how we would access the database from the browser in javascript.  As far as I can tell we would need to interact with postgres via nodejs, or python.  

NC State doesn't offer anything in this direction at all.  The longest possible reservation on VCL is only 8 hours and that's the closest possibility.  Do you think that using your own server would be problematic for you?

**Comment by macluo** [comment]
If the Firebase APIs had worked as they claim then noSQL should be good enough. Take the server site rule below as an example,

"level_data": {
          "$level": {".read": "$level <= '5' || (auth != null && root.child('user_data').child(auth.uid).child('last_level').val() +'' >= $level)"}
        },

When accessing level_data object, Firebase complains it can't find user_data. In this case, it is pretty much useless. I am glad you guys have decided to dump Firebase. LOL

**Comment by duh102** [comment]
I was somewhat expecting that @meneal, the way most people seem to handle offsite access to a DB is to make a little node/php/something shim that acts as a RESTful API to the DB. I can attempt to set up such a thing tomorrow (or I guess today rather, since it's 2 am), and if I'm still entirely baffled at the end of my work day I can just open up a DB on my server to remote access (generally not recommended for security reasons, but probably ok in our case).

**Comment by duh102** [comment]
Did some initial work with a sqlite database in 9de615d769d2bb620017b2a90fcc747d01349205, so far, pretty much all of the read-only attributes of the DB are exposed to a RESTful API (which I will eventually document), going to dive into doing logins and stuff now.
The only change for us will be that our deployment platform will have to start node on server.js and open up port 3000 (configurable), then our app can talk to the database through it.

**Comment by meneal** [comment]
So I've been looking at this a little bit and it seems like it could be
possible to deploy a DB in Heroku and then actually build a separate Heroku
webapp that is a REST API that actually connects to the DB.  There's
actually something pre-built called postgrest:
https://github.com/begriffs/postgrest.  Seems like that could actually be
workable and might deal with the groupwide issue of connectivity.  I guess
the only thing is that one person would likely have to build and maintain
the entire thing from beginning to end because the rest of the group
wouldn't have access.

**Comment by meneal** [comment]
Sorry I didn't see your email until after I sent mine.  We could actually
still deploy the API to Heroku and leave everything else on Divshot.
Otherwise we'd need to run the API and a webserver on the same node.  Are
you far enough along that it would be ok for me to try to get the API part
deployed to Heroku?  I likely won't get too far on it until tomorrow.

**Comment by duh102** [comment]
Hah that's ok. Well, so far it's read-only but you should be able to deploy it and see some categories and mazes (dummy mazes that have no information in them). So far, the following verbs are read-only:
/maze/:id   : get all information about a specific maze
/mazes/:category   : list some properties of all the mazes associated with a category and the category information
/categories   :  list you all the categories available

So far I've set up four categories and two mazes (both in the first category), so you can try out the various commands (which work from a browser too, no need to use curl or whatnot).

**Comment by meneal** [comment]
Sounds good.  I'll work on it a bit tomorrow morning.

**Comment by duh102** [comment]
Ok, so I've got authorization working now (in 1a6a52e4fd480aadda251662d904ea5e810ee574). It's pretty clean and simple, all you need to do is, when attempting to do something that needs authorization, get a session token (explaining that in a sec) and then use that login token for the play session in an authorization header.
To get a session token, POST to (server)/login with {"email":(email),"password":(password)} as the data. If you have the correct login info, it'll send back a json response in the format {"token":(the token)}
For further requests, as long as your session lasts (30 minutes from the last action using the token), you just insert an authorization header into your request (whatever it might be), which looks like "authorization:(token)".
If you need to extend your session but don't want to actually perform an action, you can just do any action on /keepalive
Obviously it's not entirely finished, still need to do all the logic for the rest of the tables, but that shouldn't be all that difficult.

**Comment by meneal** [comment]
So, just to make sure I understand what's going on.  I initially thought
you were going to set up the db on your server, but what you've actually
done is create a local db and a rest api to work with it right?  Then when
the server runs it spins up the db and then fills it using the local files?

**Comment by duh102** [comment]
So, the background for this is that the clients need to talk to the database in some fashion. It's possible to open up a DB for remote login, but that opens up a whole can of security worms because someone can just slam the DB with login requests forever in an attempt to get root access, and that's no good. What I've done is put together a small node application that handles user logins and allows only certain types of requests to be made, exposed through the RESTful API, which we can then make use of in the client application through simple web requests to the server. I had it use SQLite because it's easy, but the node app can actually use any type of server you want that has a node binding.

**Comment by meneal** [comment]
Awesome.  Makes sense.  I thought that was what was going on.  Sorry to not
know what I'm doing here, but I'm trying to get going.  I appreciate your
patience with me on it.

The big thing I think is going to be whether I leave everything all in one
box together or not.  I think there will end up being two options:

- Leave the static part of the website deployed to divshot and then deploy
the db and its api on heroku.

- Serve the static part of the website and db/api on heroku.

There's also a third dark horse option that there are addons available for
heroku which could make it possible to add a regular SQL db as an addon.
I'll play around with it during the day today.

**Comment by duh102** [comment]
It doesn't really matter where the client is, as long as the DB API is in some accessible place, and the API is just a node app that uses a SQLite DB, so anywhere that can be hosted is fine as well.

**Comment by meneal** [comment]
Deploy is working now for heroku to https://axemaze-db.herokuapp.com.  I'm
going to leave it split with divshot for the static part and heroku for the
db/api.  I think that's the easiest way to handle it actually.  Once the
build is back up I'll get travis working and each push will rebuild the db
so no one else should actually need to touch the heroku setup unless
something is broken.

**Comment by duh102** [comment]
Huh, can only one assignee be assigned? Well, sorry to anyone who scrapes this and sees like 30 assignee changes. Anywho, just pushed another feature (7dfe0fa6aba635816d114d2efc3228f5d9957763) for the /play action (the join between users and mazes, how fast they did them and in how many steps), going to continue working on this. There's not a lot left for basic functionality, I think just the ability for users to submit levels and change their emails or passwords. Beyond that there might be some other things.

**Comment by meneal** [comment]
That last push actually broke some stuff I did in server.js.  Is it ok if I
switch it back?  It is the special sauce that makes heroku work.

**Comment by duh102** [comment]
I really should have been working in a different branch, which commit(s) did you do stuff in? I'll manually merge them in because it was my bad.

**Comment by meneal** [comment]
Don't worry about it.  I'm still working so I can just knock it out when I
make my changes to .travis.yml.  I just wanted to make sure that I wouldn't
cause problems for you.  The port is going to change to 8080 for local use.

**Comment by duh102** [comment]
I just merged in the port change to my branched server.js, which I'm going to quickly merge and then branch out again lol

**Comment by meneal** [comment]
Ran into what I thought might be a problem.  Travis doesn't support multiple deployment environments.  One way to handle it is to actually split into two branches and then deploy the branches separately.  Master would be the actual website deployed via heroku and then another branch, say db or something would be the db/api.  We could just split it out into another repo too.  I'm not really sure what's more inconvenient at this point.  

I guess both are fairly acceptable, you're going to need to push to a special branch if you want changes to the database or you have to push to a separate repo.  Let me know if you have an opinion one way or the other.

**Comment by duh102** [comment]
It'd probably be best to make a new repo, to be honest. What I can do is fork the project into a new repo and then delete all non-DB things (doing the inverse in this repo), that seem reaonable?

**Comment by duh102** [comment]
Forked over to https://github.com/duh102/maze to work on the server. I'll authorize all the rest of you in case you want to contribute or anything to it.

**Comment by meneal** [comment]
Only one downside occurs to me at this point.  Heroku webapps go to sleep after an hour, I'm not sure whether there would be any issue with wakeup when the app actually gets hit.  Apparently it can take some time for them to spin back up.  Originally if we would have had dual deployments we wouldn't have had that issue.

**Comment by duh102** [comment]
Well, if worst comes to worst, I can host this API on my server as well, but with less risk of my database being hacked (which would have come with exposing a plain DBMS to external access)

**Comment by meneal** [comment]
I think it should be fine man.  We'll just have to see.  I gotta eat something, but when I get back I'll try pinging the sleeping app and see how much time its taking.  Is there a way to rename and add back to the organization?  Since it might be better when graders come through that they can find everything in the organization.

**Comment by duh102** [comment]
Hm, well what I could do is just copy and paste all the necessary files into a new repo instead of forking. We'd lose history that way, but I don't know of any other way to do it...

**Comment by duh102** [comment]
I guess actually, if you want to make this super simple, branch dbdev has my changes in it so far, that might be even easier than forking or making new repos. I was just being dumb lol

**Comment by meneal** [comment]
Cool then.  I'll set it up so that the db deploys to one heroku dyno and
the game deploys to another one.  I'll set up some sort of webserver to
handle the maze display.  Been wanting to try out nginx so this is as good
a reason as any.

**Comment by meneal** [comment]
One other good side effect of this is that we will actually avoid that time
issue I was talking about before.  When the push is made everything will be
fresh at the same time.

**Comment by meneal** [comment]
Well after all of that were back in business.  Now whenever there's a push to the dbdev branch or to master they will rebuild and deploy.  The current addressing is like this:

- database: https://axemaze-db.herokuapp.com/
- maze: https://axemaze.herokuapp.com/

We can make changes there if we need to but I'm assuming it should be ok.  To fill you both in on what's actually happening here, I'm deploying the maze using express to serve it in a heroku dynamo.  I think that should be fine.  As of right now each branch is on a separate deploy so a push to master won't deploy the db or vice versa.  

I think that if we mean to keep things this way we should definitely clean up the package.json stuff in dbdev and pull anything else we don't need out.  That will end up with us having something more lightweight in terms of the actual deployment travis has to do, and space usage on the heroku dynamo.  Let me know if you are both satisfied, if so I'll clean up package.json and clean out all of the maze files from the db too.  I can also clean up all of the old divshot stuff too.

**Comment by duh102** [comment]
So I think I might've finished the db, could someone look at the API (there's a little documentation section at the top of server.js) and see if there are any other functions we may need in the client? I'll throw QA on this in the meantime.

**Comment by duh102** [comment]
Oh, I forgot to ask. Is there a way to use curl to run tests on the API through Travis or something? I've been testing locally on a server but not in an automated fashion.

**Comment by macluo** [comment]
Just a thought. Should we separate the token or keep it on a private Github/place for security reason?

**Comment by meneal** [comment]
Do you have any tests that you're running locally that you can send to me?
I can try to mochify them.

**Comment by duh102** [comment]
I'll have to make them more official, I'll email a semi-rigorous list. At present I've just been testing as I go.

**Comment by meneal** [comment]
Cool.  I was looking at some rest api clients for javascript, do you think
we could use such a thing or do you foresee rolling our own being the
best/easiest way?

**Comment by duh102** [comment]
Using a custom client is probably not that big of a deal, but I haven't really looked. Dunno who else would want to look it over but I'm probably not going to look into it tonight.

**Comment by meneal** [comment]
Can you post a few example curl commands?  I've only ever really done
interactions with api like this through a prebuilt client, so this will be
a first for me.  I'm able to get stuff out of the db with some commands
like this:

`curl -i -H "Accept: application/json" -H "Content-Type: appliction/json"
-X GET http://axemaze-db.herokuapp.com/mazes`

But I'm not sure how to do anything more complicated than that as far
actually pulling the json objects for the mazes and whatnot.

**Comment by duh102** [comment]
Just sent an email with more stuff, not nearly all of the testable things but a good mix of things to start off with. Not only that but also most of the permutations of curl commands, the only one missing is entirely bare get commands to get public data, but those are really just curl (addr) -H "content-type:applicaton/json"

**Comment by meneal** [comment]
So right now the deployed db only has two mazes in it, just the debug maze and debug maze 2, I think that's what confused me a bit.  I was looking around in there thinking that the whole levels directory had already been put in the db.  

How are you thinking of adding the level set to the db?  I guess what I'm thinking about is that every time the db goes down the entire db will cease to exist in Heroku.  And the db will go down on every push to github as things exist currently.

**Comment by duh102** [comment]
Does Heroku delete files in the directory when it goes down, not just shut down the server? The server creates a small db file when it starts the first time and then adds to it as it runs, as long as that file remains the db will persist.
And yes, I was planning on loading the contents of the levels directory into it at some point, whether through actually reading the files or manually inputting them I'm not sure.

**Comment by meneal** [comment]
Just checked, no persistence between pushed versions. So every push deletes
the db file. Probably a few ways to deal with it. I'll look into it
tomorrow.

**Comment by meneal** [comment]
I'm thinking we might want to close this out and split it out into a few new issues from here.  I just posted two, but maybe we should get the rest of it split out into some other v4 issues?

**Comment by duh102** [comment]
Yeah, let's close this and if we need anything db-wise, make a new issue for it.
