### ISSUE TITLE
Sound effects

### ISSUE THREAD

**Issue by macluo** [CSC510-2015-Axitron/maze#44]
Sound effects are needed for the beginning and the end of each level, maybe each footstep and when the knight hitting the wall etc.

**Comment by meneal** [comment]
There is actually a problem with the initial sound setup that I'll put into another issue as a bug.  I think it may be a good idea to avoid using the built-in canvasengine sound setup.  I poked around for a bit the other night and found something the might be usable.  http://buzz.jaysalvat.com/  If I can get it working it will decouple the sound from canvasengine and hopefully make sound effects easier and fix the bug I'm talking about.

**Comment by macluo** [comment]
@meneal if you are busy with DB and API testing I can give this a try.

**Comment by meneal** [comment]
Sounds good Mark.  I am definitely busy with API/DB.  Let me know if you
need help.

**Comment by macluo** [comment]
Initial test using buzz.js turned out to be easier than Canvas Engine. 4965f8feafa675cabd7f178537e2219742239535

Next is to include sound effects.

**Comment by macluo** [comment]
Just added the latest mouse acceleration feature to master & Heroku 068333672b32b730c5e49b6de5d33daaee7e5e97 Please let me know if there is any issue with the mouse and music. If it all works fine on Heroku, I will expand the feature to support event sounds and multiple sound tracks on Friday.

**Comment by macluo** [comment]
Added winning sound clip and changed the background music to sunny happy theme, which should go well with the new grass tileset 659fd335c2d333aec9d1f9983497c7572ab5a6dc 

Please test it and let me know if you think the background and winner music are too loud. Volume control on Buzz doesn't seem to be working.

**Comment by macluo** [comment]
Added step and wall-hitting sound effects. a8e54d1889cd48ab725099a5783f96022efbc4bc  They are not perfect so if you guys find any better sound clips feel free to replace them. Now all mp3 have been normalized with same volume.

**Comment by macluo** [comment]
Public folder has also been updated so you guys can try it on Heroku too.

**Comment by macluo** [comment]
Added an input device lock at level exit to prevent character from moving ae52b7a861b188219a99501093e4ea675abe5545

**Comment by macluo** [comment]
I have also included a short intro music in the [repo] (https://github.com/CSC510-2015-Axitron/maze/blob/master/sound/intro.mp3) that could be played at the beginning of each level. This feature can be enabled once we need it.

**Comment by macluo** [comment]
Closed.
