### ISSUE TITLE
Music stops suddenly

### ISSUE THREAD

**Issue by meneal** [CSC510-2015-Axitron/maze#45]
So at least in what has been deployed, music stops after you progress to level 2.  I think it has something to do with the loadout of the maze [here](https://github.com/CSC510-2015-Axitron/maze/blob/master/mazeMenu.js) on line 169.  I think that somehow on repeated loadouts the loop is somehow stopped.  I'd like to try to fix it using [buzz](http://buzz.jaysalvat.com/).  Potentially that could pull the functionality out of canvasengine and may prevent the issues that we're seeing on each load.  If there is some easier way that someone sees quickly it would obviously get rid of a bunch of work so that would be great too.

**Comment by macluo** [comment]
Yes, thanks for pointing this out. I have been testing Divshot site exclusively on Safari and music all worked fine. Now when I switched to Google Chrome, music did stop at level 2.

**Comment by meneal** [comment]
Weird!  I wonder why it stops on Chrome but not Safari.  I think there's a whole thing with HTML 5 compatibility.  You know what I just tried it in firefox too and it works there.  It's just a problem in chrome.  Perhaps it's not worth fixing at that point.

**Comment by macluo** [comment]
I thought CanvasEngine was supposed to be good at handling sound and now I am convinced that it is otherwise when dealing with multiple scenes. Even on Safari, I had trouble stopping the music or switching track. I guess eventually we will need to put music and sound effect on HTML5 because it is easier.

**Comment by meneal** [comment]
The weird thing about this is that now that it's on Heroku it's working at
least on chrome.

**Comment by macluo** [comment]
Should we close it? Or we can just let HTML5 or other sound engine take care of music and sound effect?

**Comment by meneal** [comment]
I feel like at this point if it ain't broke we shouldn't try to fix it.  If
we can get sound effects working using canvas engine there's no need to
make a change.  Since the sound is working now cross browser I think we
should leave it be.  I'll close.  I opened it.
