### ISSUE TITLE
Build Failing

### ISSUE THREAD

**Issue by meneal** [CSC510-2015-Axitron/maze#46]
It looks like something in this [commit](https://github.com/CSC510-2015-Axitron/maze/commit/adb6d8b06e1d8bfa8d95581da630c2c3e6ae5b1a) broke the build.  The output carries through from build 63 to build 64.  Output is [here](https://travis-ci.org/CSC510-2015-Axitron/maze/builds/54470861).  I wouldn't post a bug for it, but I'm actually working with travis today for the heroku deployment of the dbserver.  It looks to be some interaction between mazemenu.js and test-themenu.js.

**Comment by macluo** [comment]
It has been fixed.

**Comment by meneal** [comment]
Awesome, you're quick man!

**Comment by macluo** [comment]
Forgot to run the test before merging to master. My bad. Did a quick patch. It lowered the branch coverage a bit but the test is passed now. Will improve coverage when other features have been added to the game menu.
