### ISSUE TITLE
Test API

### ISSUE THREAD

**Issue by meneal** [CSC510-2015-Axitron/maze#50]
Write tests for API once client is complete.

**Comment by duh102** [comment]
I'll start developing the things that should be tested, pending the client lib to actually perform the tests.

**Comment by meneal** [comment]
That would actually be really helpful to me.  Then I can just write the
rest of it to the tests and make sure it works.  Are you going to write
them in mocha?

**Comment by duh102** [comment]
I haven't done Mocha before but I can certainly use it. I'm guessing I'd just put some placeholders in there if you haven't defined names for the different functions yet, or should I just copy the API names for things in the expectation you'll name the functions the same as well?

**Comment by meneal** [comment]
In reality I think most of the functions are already defined in there, but
if you notice something missing just put what ever you think for a function
name and I'll just use the same name and the same returns.  Worst case
we're working simultaneously and one function call is the wrong name on one
side or the other, but we can just get that sorted out if it comes up.
Shouldn't be a big deal to fix.  Take a look at some of the promise stuff
in the mocha api, since as you well know a bunch of these are async.  If
you have trouble though, no big deal, just setting up the structure of the
describes and its should be a big help.

**Comment by meneal** [comment]
Tests are now complete.  Probably could add a few more, but these are a good enough start to close this out. Closing.
