### ISSUE TITLE
Remove alert on level completion

### ISSUE THREAD

**Issue by ktspence** [CSC510-2015-Axitron/maze#52]
Remove the alert message on level completion. Partially in preparation for a less-intrusive completion message, and partially to make repeated testing more efficient for developers.

**Comment by macluo** [comment]
Alert popup will be replaced with event sound triggered by level completion #44

**Comment by duh102** [comment]
I believe c690d142415a531603ec8ed2c012f894fa9225f4 fixes this issue. Reopen if this is not the case.
