### ISSUE TITLE
DB needs real data

### ISSUE THREAD

**Issue by meneal** [CSC510-2015-Axitron/maze#54]
So right now the db has nonsense data in it from testing.  We should clean it out and put in the and some base user.

**Comment by duh102** [comment]
Should we retain the testing users, or remove them as well? I can go in and manually delete users with no issue.
I also just cleared out the testing mazes (And all the duplicate ones).

**Comment by duh102** [comment]
I can start working on porting the existing levels over, do we want to include all of them or only a smattering?

**Comment by meneal** [comment]
Either way on the testing user.  If we don't retain them we'd still need
some other starter user.  As far as the levels, I think for now we can
include all of them, since we don't have other content to replace them
really yet.

**Comment by duh102** [comment]
I haven't given any of the levels names, but they're now all in there: http://axemaze-db.herokuapp.com/mazes/category/1
If you give me names I can happily put them in.

**Comment by duh102** [comment]
Actually, I can just get some names from Firebase, I'll go do that.

**Comment by meneal** [comment]
Cool.  That's fine.  I was going to say just use a fantasy name generator
or something.  I just made those fb names up really quick.

**Comment by duh102** [comment]
Well, I'll call this closed, when the client hookups with the API work we can add more real maze data.

**Comment by macluo** [comment]
Is there a reason the first maze begins with id 19? Need to know this in case 0-18 would be reserved for something else.

**Comment by duh102** [comment]
Nope, they auto-index starting at 1 and we had 18 junk mazes (the first two
and a bunch of submissions from testing).

**Comment by macluo** [comment]
Okay. Thanks.

**Comment by meneal** [comment]
http://axemaze-db.herokuapp.com/maze/1, returns this:

`{
    "response": "maze not found",
    "query": "1"

}`


And when you run http://axemaze-db.herokuapp.com/mazes/category/1, you get
back the following:

`{
    "category": 1,
    "categoryName": "Small Mazes (5-10)",
    "mazes": [
        {
            "mazeno": 19,
            "displayName": "Dungeon of Smallness"
        },
        {
            "mazeno": 20,
            "displayName": "Dungeon of Less Smallness"
        },
        {
            "mazeno": 21,
            "displayName": "Dungeon of the Ogre"
        },
        {
            "mazeno": 22,
            "displayName": "Dungeon of the Goblin"
        },
        {
            "mazeno": 23,
            "displayName": "Dungeon of the Dwarf"
        },
        {
            "mazeno": 24,
            "displayName": "Dungeon of the Warlock"
        },
        {
            "mazeno": 25,
            "displayName": "Dungeon of the Imp"
        },
        {
            "mazeno": 26,
            "displayName": "Dungeon of the Troll"
        }
    ]
}`


If the mazes should be ordered starting with one then I would think
the first maze in category 1 should be mazeno one right?

**Comment by duh102** [comment]
They're auto-indexed, meaning they started numbering at 1, but I deleted
18, so the only remaining ones are id 19+.

**Comment by meneal** [comment]
Gotcha.  That makes sense.

**Comment by macluo** [comment]
The first id being 19 is not an issue. The script will first get whatever parameters they need from the remote db before it sets up the maze.

**Comment by macluo** [comment]
I see some data are in arrays already. This actually saves me a lot of work. lol

**Comment by meneal** [comment]
Good, so the apiClient is working for you?

**Comment by macluo** [comment]
I am lazy so …. I am trying to avoid reading code. LOL For loading the mazes, I read the output from Heroku site and then improvise. I would use apiClient for authentication and others.

**Comment by macluo** [comment]
There is a very small typo in the mazeJSON string of maze 19. 
```
\"board\":[[6,5,6],[12,1,8]]}"
```

It should be
```
\"board\":[[6,5,3],[12,1,8]]}"
```

This minor error actually blocks the exit. The knight now can't go anywhere.

**Comment by duh102** [comment]
Should be fixed, I updated it in the DB.
