### ISSUE TITLE
DB has strange behavior on adding new mazes

### ISSUE THREAD

**Issue by meneal** [CSC510-2015-Axitron/maze#55]
So, I know there are a good number of mazes in the db, but currently the only ones that show up in categories are the dummy mazes.  That doesn't really make sense because the new mazes that were generated passed in data to be added to the small size category.  Not sure why that's happening.  Right now there are 10 mazes, but only 2 in categories.

**Comment by duh102** [comment]
So, the behavior I put into the API is as follows, and explains what's happening:
* mazes with users attached to them (added through the API) are considered to be first and foremost user mazes
* mazes without users attached to them (manually added by us as DBAs) are considered to be first and foremost 1st party mazes, vetted and okayed by us

User mazes are not ever shown in category view, while 1st party mazes are.
I actually forgot to take out the debug code that adds the fake mazes and users, I'll clean out the DB and push the non-debug code to heroku. If we want to change the above behavior that's fine, but I thought the separation would be good in case we ever get some nazi-themed mazes or whatnot.

**Comment by meneal** [comment]
I actually think this is actually a great.  Not a bug, a design feature!
Seems like it would be good to keep that separation.

**Comment by meneal** [comment]
I'll close this.
