### ISSUE TITLE
Game down on Heroku

### ISSUE THREAD

**Issue by meneal** [CSC510-2015-Axitron/maze#57]
Looks like server.js got deleted somehow in the root.

**Comment by duh102** [comment]
Are you using axemaze-db or axemaze? axemaze has never worked as far as I can tell. axemaze-db is working.

**Comment by meneal** [comment]
Axemaze actually was working the last time I checked.  I just checked the
logs, and it's an issue with server.js.  I made a quick express app to
serve everything in the public folder and then pushed it, but it must have
been deleted (probably by me) a few days ago, and I just missed that it had
taken down the game.  I'm getting totally killed right now with game ai
stuff so I haven't been back around to it for a few days.  It's back up and
running now.  Should we be serving the designer too?  I'll close this since
it's fixed.  Let me know in the future if axemaze is down I should be able
to get it fixed without much of a problem.
