### ISSUE TITLE
MazeDB hookups for designer

### ISSUE THREAD

**Issue by duh102** [CSC510-2015-Axitron/maze#58]
Save/load from MazeDB from/into designer

**Comment by macluo** [comment]
This issue has been pending for 3 days. Does anyone has planned to work on this feature? If you guys are busy, I can get this started.

**Comment by meneal** [comment]
I'm still working on this side menu thing.  It will likely take me awhile
since I have a lot to learn just to get it all to work.

**Comment by duh102** [comment]
I actually just put in a loading feature that modifies the designer page with a valid maze, so it should be fairly easy to implement.

**Comment by macluo** [comment]
Cookie feature is also added by remoteDB object. You guys can copy & paste the code or break down the mazeMenu.js so designer can load the common js file too. Okay. I will leave this to you guys and work on something else.

**Comment by duh102** [comment]
I'm going to split out the remoteDB into it's own js so it can be shared between the designer and the game, just an fyi.

**Comment by macluo** [comment]
:+1:

**Comment by duh102** [comment]
Should be done, I'm able to save and load mazes to my user profile just fine (to test, log into dummy1@dum.my and try it out).
