### ISSUE TITLE
Maze rendering

### ISSUE THREAD

**Issue by duh102** [CSC510-2015-Axitron/maze#6]
Relies on #2 for exact format of maze but should be decouplable

**Comment by duh102** [comment]
Rendering is working well so far, except for a problem (easily detected in 0275f21e42fc4468088310731b146839d7d51180) where if you load a level and then attempt to render that level in the callback, it occasionally will just not work. I'm uncertain why.

**Comment by duh102** [comment]
Rendering fixed (7cfc951c30d890b32c88764b901b20ea428e07cb), it was a conflict between canvas.ready() and the rest of the code being ready.

**Comment by duh102** [comment]
Making a large rewrite of many portions of the renderer, due to engine limitations. See https://github.com/CSC510-2015-Axitron/maze/issues/20#issuecomment-74807577 for an explanation of why.

**Comment by duh102** [comment]
So does anyone feel brave enough to do the merge of mazerender and prettiermaze into master?

**Comment by macluo** [comment]
The scrolling maze is amazing. You the man! I could try to do the merge over the weekend if you guys don't have time. LOL I guess the scrolling maze might break the backtrail module, right? But I will see what I can do.

**Comment by duh102** [comment]
Yeah I'm wary of possible conflicts, more than pressed for time. Depending on how things go, I could try doing the merge, I just don't want to accidentally break everything. But I suppose that's what reverts are for.

**Comment by macluo** [comment]
Just merged it and It went well 632cceb1c18707c5b6486db25691f363a07e3f3c except that all tests passed but the status on the page says "test failed." I will combine backtrail into your test file tomorrow.

**Comment by duh102** [comment]
Yeah, I had that happen once on my end as well, I'm not sure where it came from. Might be some other file with similarly named vars interfering.

**Comment by meneal** [comment]
Mark:  If you mean to rework tests, please keep them separate with a filename prepended with "test-", probably in your case "test-backtrack.js".  If we mean to go to mocha based tests I or you would need to rework your tests for mocha, and for that purpose keeping them separate is going to best.

**Comment by macluo** [comment]
Cool. I will create a new one to test trail in mazeRenderer and scrolling maze.

**Comment by duh102** [comment]
You will probably want to have the trail render on bgCanvas, the normal canvas is essentially stationary because the player doesn't move at all. Not only that, but you can use whole-maze coordinates with bgCanvas, whereas with the normal canvas you'd have to move the trail around each time the player moved.

**Comment by meneal** [comment]
I found the failed test.  It's coming through in my tests too.  Somehow you're returning non-boolean values, not a 0 or 1 on line 141 of MazeModel.  So you're expecting true or false but getting 4.

**Comment by duh102** [comment]
Gonna close this because the basic feature is complete. Open a new issue if there's a problem with it or another feature needs to be added.
