### ISSUE TITLE
Maze designer cannot click single cells

### ISSUE THREAD

**Issue by duh102** [CSC510-2015-Axitron/maze#67]
At least in FireFox, didn't have time to check other browsers.

**Comment by ktspence** [comment]
This might have something to do with the wallOver and wallClick calls being to the same function.

**Comment by ktspence** [comment]
Fixed the problem. Inside the wallClick function, which was hybrid for mouseOver (while down) and mouseClick, there was a check to see if the mouse was down, that wasn't applying if the reason for invoking was a click.
