### ISSUE TITLE
Maze main menu

### ISSUE THREAD

**Issue by duh102** [CSC510-2015-Axitron/maze#7]

**Comment by meneal** [comment]
What features should a main menu actually display?  The things that come to mind are the following:

-load map
-random map (proceedurally generated map)
-start game (could just run the game with a random map, or we could have users actually load maps first and then hit start)
-save game?
-quit?  
-some kind of simple graphical splash to go along with the menu

I'm not sure whether quit or save game make sense in the context since you'd just close a tab or window to quit I guess.  And I'm not really sure what save would do.  What do you think?

**Comment by macluo** [comment]
I guess #17 may combine with this if we decide to put this component on a single html page. I can work on the menu a bit on Friday if you guys don't mind. 

"Start" "Level" "Random" "Player Name" "Save game" etc are what i have in mind. I guess if the site can save the cookie maybe we don't even need to add "Save game" button.

**Comment by duh102** [comment]
Maybe something like this? http://i.imgur.com/UIxVVe4.jpg?1 Only problem is, I'm not sure how to handle generated vs loaded levels. Also, a dropdown might be too simple if we make a lot of levels, and this would have to change if we had user-created levels.

**Comment by meneal** [comment]
I like what you've posted.  I think it could make sense to actually have a more static page outer page as the actual main menu with all the same buttons, but have it actually be a page without the canvas.  If we do that someone could work on the main menu without having the actual game working.

So functionality would be something like this 

Static Main Menu Page ==> Game page ==> static main menu pa

[This game](http://www.kongregate.com/games/HyperNexus/the-cave-of-tman) has a similar set up to what I'm thinking of.

**Comment by macluo** [comment]
While working on the game menu javascript, I need to decide whether to replace maze.js with a big chuck of code from /test/test_mazeRender.js written by Will or leave maze.js alone and move the code to the new JavaScript file. Should we have a separate file for spritemap?  Any suggestion?

**Comment by duh102** [comment]
In theory, we could (and if we want, can) have the user select between tilesets, but for now we should probably stick with one. Moving it to a new file would be fine, imo, no reason to shoehorn that whole big thing into an executable file when it's just some data.

**Comment by meneal** [comment]
I agree with will.  I think for now it's best to stick to one tileset.

**Comment by macluo** [comment]
All right. Thanks. Just created a new branch called mazeMenu 0ef12282460d7092254edbd2524141299a62b749 where a new file mazeMenu.js has been created. The game page is now on index.html . The image has not been finalized! Once we decide the buttons, texture, and color theme for the game menu image we can go ahead and implement rest of the features. We could also implement a static main menu page before this game page like Matt has suggested.

**Comment by macluo** [comment]
Just pushed a4c261033721a8e103b5d5ff7cb5b7fab10d1470 Does anyone know why the text replaced by jQuery at line 25 of https://github.com/CSC510-2015-Axitron/maze/blob/a4c261033721a8e103b5d5ff7cb5b7fab10d1470/mazeMenu.js lose the original CSS style? You can remove the comment to see the step count.

**Comment by duh102** [comment]
I think it's because that div has a span inside it where the style for the text is actually applied, and you replace that span with the number, so the style is lost:
 <div class="gwd-div-sgwf gwd-div-a5rr gwd-div-kswq" id="dsp_steps">
<div class="gwd-div-s0lj gwd-div-fdrl gwd-div-k1ye"><span class="gwd-span-gtjf gwd-span-7i1h gwd-span-wbjx">23</span>
</div>

**Comment by macluo** [comment]
Ha, I see. Thanks.

**Comment by macluo** [comment]
Now the game menu can display time, steps and will show a pop-up when player completes the maze. 386e089ab9c233bc61cafbbf389924f1378bf239

**Comment by macluo** [comment]
854f651a0b4c1b59b3f35e3e7709353d6de0fd20 now game should load next available maze at the end of each level. We may not want this but we can change it in the future. This thread is getting too long so I will open a new issue report.

**Comment by macluo** [comment]
Merged to master 3912ae73d84838384e795121b50cc8de2f9d1345 Closed for now.
