### ISSUE TITLE
Load procedural maze

### ISSUE THREAD

**Issue by duh102** [CSC510-2015-Axitron/maze#71]
Add sidemenu option to load procedural maze

**Comment by meneal** [comment]
This is done.  Probably need someone to notify me once new algorithms are added so that I can make sure that the different types are loading up correctly.

**Comment by duh102** [comment]
Do you use the /maze/gen/algorithms call to get the algorithms? Because that should be all you need.

**Comment by meneal** [comment]
Yep.  I am using that.  I just want to make sure that it's working right
when more algorithms are added.  It should work no problem though.

**Comment by duh102** [comment]
Sounds good.
