### ISSUE TITLE
Continue loading mazes in category from loaded maze index

### ISSUE THREAD

**Issue by duh102** [CSC510-2015-Axitron/maze#75]
When user selects a maze from a category, and completes it, user's next maze comes from the same category.

**Comment by macluo** [comment]
Just to let you guys know that I hold off this for another day until tomorrow or sidemenu and its related functionality is completed. In case the feature you need from remoteDb has not been implemented, just code the interface and I will finish and complete the rest.

**Comment by macluo** [comment]
Done in 0fff050130945952893636f975532a044b6c1b01 Let me know if there is any issue.

**Comment by macluo** [comment]
0f4cbce134838012e4b23322451df8991ec202b This task is completed. Open a ticket if there is any issue.
