### ISSUE TITLE
Function for shortest path length to help with start/end selection in algorithms.

### ISSUE THREAD

**Issue by ktspence** [CSC510-2015-Axitron/maze#76]
The current procedural generation algorithm could benefit from such an algorithm to increase the quality of start/end point selection. Will also be useful for other procedural generation algorithms. An A* search would be good.

**Comment by meneal** [comment]
Seems like this is actually milestone 6 since we added it today.

**Comment by ktspence** [comment]
Yep, I picked the wrong one in the list.

**Comment by ktspence** [comment]
Also this is done. Just added the code to dbdev.
