### ISSUE TITLE
List of Functional Tests

### ISSUE THREAD

**Issue by meneal** [CSC510-2015-Axitron/maze#77]
Need list of final functional tests.

**Comment by duh102** [comment]
Currently fleshing out the documentation for the DB api, going to put it into the readme.md in the repo.

**Comment by duh102** [comment]
Reference complete in 93e2075e570917d9d4cfdc635350585eda1a2cb1, let me know if it's vague anywhere. Still developing test paths.

**Comment by meneal** [comment]
The readme on this is really nice.  It gives a really nice run down on how to use the api.

**Comment by duh102** [comment]
Anyone who wants to start implementing the tests in https://github.com/CSC510-2015-Axitron/maze/blob/master/OldTest/api_tests.txt should feel free, writing out the tests themselves will still take a while.

**Comment by duh102** [comment]
Just pushed a semi-finished series of tests. I can't think of any more that would cover anything not already covered, more just combinations of things (like logged in vs logged out of the same feature), so I think that's most of what needs to be done.
If anyone wants to write more, be my guest, but I think that's about all that's needed.
Reopen if necessary, gonna close it.
