### ISSUE TITLE
No escape from designer

### ISSUE THREAD

**Issue by meneal** [CSC510-2015-Axitron/maze#79]
Once you're in you're trapped in there!  Could use some sort of button to get back out to playing the game.

**Comment by duh102** [comment]
Are you taking care of this?

**Comment by meneal** [comment]
Not currently.  I'm still trying to figure out how to get the user id once the user is logged in.  I just noticed and figured there should be some sort of way back to playing the game.

**Comment by duh102** [comment]
Ok, I'll take care of it. You can check if the user's logged in by checking remoteDB.isLogon, and then if so, the user's id is remoteDB.userID .

**Comment by meneal** [comment]
Thing about that is when to actually check for the mazes.  So first thing
when the game loads up you won't be logged in.  I'm really just trying to
figure out at what point to check whether they've logged in and then pull
the id number.  I'm trying adding it in at various points after the login
takes place.

**Comment by duh102** [comment]
Why not at every time they click the levels button? You'd need to update the levels completed every time they open it anyway, in case they've completed a level in the meantime.

**Comment by meneal** [comment]
I actually just put it in the callback on line 720.  It's just a function
that builds the entire current user list whenever they log in.  Do you
think that's a bad place for it?  If i update it when the levels button is
pressed then we have two api calls instead of one every time the levels
button is pushed...

**Comment by duh102** [comment]
Just thinking that since it changes every time they complete a level, you might want to update it when they open the levels bar, but we can push that off to theoretical polish.
