### ISSUE TITLE
User input validation

### ISSUE THREAD

**Issue by duh102** [CSC510-2015-Axitron/maze#8]
User shouldn't be able to move smily through walls (relies on #2 but should be decouplable)

**Comment by duh102** [comment]
Forgot I added this in f8b6d26883c2d4dbbfb3a043e02ddefa5638d085, marking as QA but it should be pretty much finished (tests are in model test)

**Comment by duh102** [comment]
Gonna close this, reopen if it breaks somehow.

**Comment by meneal** [comment]
Are these tests additional to what I've already put into mocha?
