### ISSUE TITLE
User's level completion information not saved when loading from sidemenu

### ISSUE THREAD

**Issue by meneal** [CSC510-2015-Axitron/maze#80]
The basic problem is that a user's information isn't updated when they complete a maze if they start from some arbitrary point.  The rest of the maze menu thinks they are wherever they were on the cycle of mazes from start to finish.

This may well be fixed by whatever fix is made to make mazes continue loading from wherever a user points the system.

**Comment by macluo** [comment]
I can fix that tomorrow.

**Comment by macluo** [comment]
Should be fixed in 0fff050130945952893636f975532a044b6c1b01 If not, let me know.
