### ISSUE TITLE
Use maze distance function to improve genRecursiveBacktracker(...) starting point selection

### ISSUE THREAD

**Issue by ktspence** [CSC510-2015-Axitron/maze#81]
Currently the algorithm picks the endpoints at random corners. This works because the minimum distance between the corners for an NxN maze is always at least 2N-2 steps, but there are often clearly more relevant points nearby. The shortest path distance algorithm can be used to iteratively move the points in steps that increase the shortest path between them.

**Comment by duh102** [comment]
I think this is done? It doesn't pick endpoints at corners anymore, at least.

**Comment by ktspence** [comment]
Yes.
