### ISSUE TITLE
Feature is needed for the "GOTO" button on the game menu

### ISSUE THREAD

**Issue by macluo** [CSC510-2015-Axitron/maze#87]
No task has been assigned to this button, so should we delete it?

**Comment by meneal** [comment]
My vote is for deleting it.  I don't really see what point it serves now.

**Comment by ktspence** [comment]
Yeah I think a lot of the functionality it *would* have is accounted for by the Level button.

**Comment by duh102** [comment]
Yeah, I think it's pretty useless. I'll take it out real quick.
