### ISSUE TITLE
Retooled maze interactions

### ISSUE THREAD

**Issue by duh102** [CSC510-2015-Axitron/maze#89]
Change the way users interact with the system so that they don't know whether they're getting a hand crafted maze or a randomly generated one, but record whether or not they liked a maze.

**Comment by meneal** [comment]
So this is partially done.  There are two elements missing at this point:

 - The box indicating whether they liked the maze or not
 - A set of fake names to give to procedurally generated levels, right now they're just posting up the names of the algorithms.

Sorry I didn't make an issue instead of sending out an email.  I'll make another issue for the analytics piece and assign it to myself to knock out when these last two things are done.  The name part is really easy, I just didn't think of it until today, but I likely can't get back around to this by tomorrow since I have to try to figure out the python stuff.

**Comment by duh102** [comment]
I'm working on this a bit, I've got it so that as the user chooses that they liked or disliked a maze, it will change the maze bias to be more of the thing they were on or not. Just gotta clean up a few things and I'll push it.
As for names, we can actually just replace that name thing with something common to both, like the size of the maze.

**Comment by duh102** [comment]
Looks like we have some scoping issues in mazeMenu, going to reformat it a bunch.

**Comment by macluo** [comment]
To achieve that with a minimal amount of effort I would let RemoteDB.getNextMaze() method handle that or modify logics in the method.

**Comment by duh102** [comment]
Undid my reformat, there's a lot of tangled references that I didn't want to mess with.
So now, the choices the user makes influences the coarse class of maze selected (random or handcraft), but the handcraft still only loads from small. I'm unsure what controls that and I don't want to break it, does anyone want to take a stab at that, or tell me where to pick at?

**Comment by macluo** [comment]
remoteDB verifies with currentLevel global variable (0 ~ 3, sorry about the naming) to see which category the current maze is in. The method in its current form loops all the mazes from small to large if you remove ++currentLevel in getNextMaze() then it will rotate within current category. I am tied up with another RoR project but I will pick up anything left to do tomorrow.

**Comment by duh102** [comment]
I think it might be done? It might need some tweaks to the way it selects a seed for the procedural maze generation (I didn't check the math extensively, I think the large and huge mazes cluster around 35ish width and height), but it doesn't show the name of the mazes (in the case of hand drawn) or the algorithm (in the case of procedurally generated), just the size of them, and it picks the mazes properly.

**Comment by meneal** [comment]
Seems to be working just fine to me at this point.  I'll add in the analytics stuff.  If you're happy with it we can just close it.

**Comment by duh102** [comment]
The only thing I'm not happy about is the first maze is always the same. I'm not sure it's easily changable, if it is that'd be good to do, but it's not a huge deal.

**Comment by meneal** [comment]
I agree, not a big deal.

**Comment by duh102** [comment]
Alright, well if someone wants to fix that, feel free to reopen this or make a new issue.
