### ISSUE TITLE
User Character

### ISSUE THREAD

**Issue by duh102** [CSC510-2015-Axitron/maze#9]
So far I just have a smiley, do we want something else?

**Comment by meneal** [comment]
I think it might be a good idea to use something more interesting.  I'm looking at some of these different free to use icons that are at this guy's site: http://untamed.wild-refuge.net/rmxpresources.php?characters

How about the hulk?  :)  I'll try to figure out how to actually add in something like that.

**Comment by duh102** [comment]
If we use a fancy sprite like that, maybe we should also make the maze look prettier. Unfortunately I'm no spriter, but maybe I can scare up some proper perspective resources to match those sprites. I'll open another feature issue for a nicer looking maze.

**Comment by meneal** [comment]
I'm not much of a spriter either actually.  I tried to do a bit of stuff with the built in canvas sprite functions, but didn't have a lot of luck:

http://canvasengine.net/doc/?p=extends.spritesheet

I'll keep messing with it though once I can get the test pipeline in #21 working.

**Comment by duh102** [comment]
Forgot that I was going to use the little knight sprite from the spritesheet I'm using in #20 for this. I'll slap feature dev on this.

**Comment by duh102** [comment]
I think this guy's pretty much done.
